### PR TITLE
updated sirname

### PR DESCRIPTION
**Pull request by jmdvinodjmd**
Changed from Vinod 'Kumar Chauhan' to Vinod Kumar 'Chauhan'.

### CODE REVIEW

**Review by lawrennd — CHANGES_REQUESTED** [review]
File name and directory of PDF also need fixing for new links to work.

**Comment by jmdvinodjmd** [comment]
Dear Neil Lawrence, thanks for merging the other pull request. My apologies for not requesting the changes correctly. It appears you need to accept this pull request also as the other pull request only changed file/folder names and at the moment the paper link are not working. Once again thanks for your time and apologies for multiple pull requests.

**Comment by lawrennd** [comment]
Thanks for bumping! Should have spotted this myself.

**Comment by jmdvinodjmd** [comment]
Many thanks, I really appreciate your time.

**Pull request merged**
